### PR TITLE
fix design Auth pages

### PR DESCRIPTION
**Pull request by mytechworker**

### CODE REVIEW

**Comment by Yacobolo** [comment]
@ujjwal51

**Comment by ujjwal51** [comment]
# Fix this changes

1. According to Figma, there should be some padding or margin at the top of the page, but the current design lacks any padding or margin at the top. (Fix all pages accordingly)

Screenshot from 2024-01-15 15-57-08

2. There should be no extra padding at the bottom of the page. (fix all pages with same issue)

Screenshot from 2024-01-15 15-57-00


3. The logo is not visible on the Sign-Up page. Could you please check and ensure that the logo is properly implemented and displayed? (fix logo issue)

Screenshot from 2024-01-15 15-56-53

**Comment by Yacobolo** [comment]
also not purple

**Comment by ujjwal51** [comment]
> which browser are you using ? @ujjwal51

Chrome

**Comment by ujjwal51** [comment]
> > which browser are you using ? @ujjwal51
> 
> Chrome
but as far as I know, the pages should be responsive for any browser and screen size. Please correct me if I am wrong.

**Comment by mytechworker** [comment]
I am done with above 3 feedback. You can check and let me know if any other feedback and changes are push in this pr.

**Pull request merged**
